[package]
name = "playground-rust"
version = "0.1.0"
authors = ["hakuginn220 <hakuginn220@white-falls.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
